name: Terraform Format

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  terraform-fmt:
    name: Terraform Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Check Terraform formatting
        run: terraform fmt -check -recursive

      - name: Show Terraform version
        run: terraform version
