name: Terraform Security

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  terraform-security:
    name: Terraform Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init -backend=false -input=false

      - name: Terraform Validate
        working-directory: environments/dev
        run: terraform validate -no-color

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --recursive

      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@<verified-commit-sha>
        with:
         version: v0.58.2

      - name: Run Trivy Terraform security scan
        run: |
          trivy config \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            .
